### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JuanJoseAriasJaramillo** [thexaero/xaero-minimap-translations#5]
How to recreate: No idea, it just happened after i added some mods.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-06-13 17:38:39
Description: Unexpected error

java.lang.RuntimeException: Xaero's World Map (1.20_1.30.4_fabric) has crashed! Please report here: bit.ly/XaeroWMIssues
	at xaero.map.CrashHandler.checkForCrashes(CrashHandler.java:15)
	at xaero.map.MapProcessor.onRenderProcess(MapProcessor.java:548)
	at xaero.map.events.Events.handleRenderTick(Events.java:85)
	at net.minecraft.class_757.handler$bhi001$xaeroworldmap$onRenderEnd(class_757.java:4116)
	at net.minecraft.class_757.method_3192(class_757.java:979)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.util.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider com.twelvemonkeys.imageio.plugins.webp.WebPImageReaderSpi could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:189)
	at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:113)
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:134)
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at xaero.map.MapWriter.loadBlockColourFromTexture(MapWriter.java:895)
	at xaero.map.region.MapPixel.getPixelColours(MapPixel.java:54)
	at xaero.map.region.MapBlock.getPixelColour(MapBlock.java:53)
	at xaero.map.region.MapTileChunk.updateBuffers(MapTileChunk.java:93)
	at xaero.map.region.texture.LeafRegionTexture.preUpload(LeafRegionTexture.java:52)
	at xaero.map.MapProcessor.onRenderProcess(MapProcessor.java:483)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: com/twelvemonkeys/lang/Validate
	at com.twelvemonkeys.imageio.spi.ReaderWriterProviderInfo.<init>(ReaderWriterProviderInfo.java:92)
	at com.twelvemonkeys.imageio.plugins.webp.WebPProviderInfo.<init>(WebPProviderInfo.java:41)
	at com.twelvemonkeys.imageio.plugins.webp.WebPImageReaderSpi.<init>(WebPImageReaderSpi.java:49)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 21 more
Caused by: java.lang.ClassNotFoundException: com.twelvemonkeys.lang.Validate
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 30 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at xaero.map.CrashHandler.checkForCrashes(CrashHandler.java:15)
	at xaero.map.MapProcessor.onRenderProcess(MapProcessor.java:548)
	at xaero.map.events.Events.handleRenderTick(Events.java:85)
	at net.minecraft.class_757.handler$bhi001$xaeroworldmap$onRenderEnd(class_757.java:4116)

-- Affected level --
Details:
	All players: 1 total; [class_746['ShaderName'/9574, l='ClientLevel', x=-56.70, y=106.00, z=1312.34]]
	Chunk stats: 1521, 625
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1891188 game time, 2048853 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Sleep Tight Generated Pack

-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 255839656 bytes (243 MiB) / 717225984 bytes (684 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA T1200 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1fbc
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2879
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9a60
	Graphics card #1 versionInfo: DriverVersion=30.0.101.1404
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34535.82
	Virtual memory used (MB): 15400.05
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 7.29
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		adventurez: AdventureZ 1.4.18
		appleskin: AppleSkin 2.5.0+mc1.20
		cenchants: Combat Enchants 2.14.7
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.57
		do_a_barrel_roll: Do a Barrel Roll 3.0.0-beta.1+1.20
			cicada: CICADA 0.4.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		fabric-api: Fabric API 0.83.0+1.20
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a27
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c927
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b27
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d127
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b27
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b27
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f27
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b27
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b327
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b327
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b27
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b27
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe27
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.10+b3afc78b27
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b27
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b27
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b27
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b327
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a27
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b27
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b27
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da27
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b327
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b27
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b27
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c627
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b27
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b27
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b27
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b27
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b327
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b27
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b27
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b27
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b27
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b27
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b27
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b327
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b27
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b27
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b327
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b27
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.4+b3afc78b27
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d27
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b27
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b27
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b27
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b27
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b27
		fabricloader: Fabric Loader 0.14.21
		friendsandfoes: Friends&Foes 1.9.0
		giantspawn: Giant Spawn 4.5
		guardvillagers: Guard Villagers Fabric 1.20-1.2.0
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 14.0.0.11
		midnightlib: MidnightLib 1.4.0
		minecraft: Minecraft 1.20
		moonlight: Moonlight 1.20-2.5.0
		morebows: More Bows Restrung 1.0.11+1.20.x
		naturallychargedcreepers: Naturally Charged Creepers 3.2
		netherportalspread: Nether Portal Spread 7.5
		sleep_tight: Sleep Tight 1.20-1.1.1
		sound_physics_remastered: Sound Physics Remastered 1.20-1.1.1
		spidersproducewebs: Spiders Produce Webs 3.1
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.6
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.9
		treeharvester: Tree Harvester 8.1
		xaerominimap: Xaero's Minimap 23.4.4
		xaeroworldmap: Xaero's World Map 1.30.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.0.0+1.20
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
	Launched Version: fabric-loader-0.14.21-1.20
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA T1200 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.79, NVIDIA Corporation
	Window size: 1920x1200
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: en_us
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50G

**Comment by thexaero** [comment]
YetAnotherConfigLib

And this is not the place to report bugs.
